name: design_patterns_dart
description: Dart examples for all classic GoF design patterns.
version: 0.20.0
homepage: https://refactoring.guru/design-patterns
repository: https://github.com/RefactoringGuru/design-patterns-dart
issue_tracker: https://github.com/RefactoringGuru/design-patterns-dart/issue

environment:
  sdk: '>=2.15.0-68.0.dev <3.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  lints: ^1.0.0

flutter:
  uses-material-design: true
